language: java

sudo: false

install: true

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
  
cache:
  directories:
    - '$HOME/.m2/repository'
    
deploy:
  provider: releases
  overwrite: true
  api_key: "b677faaebc6b00b39b322931269bbc1adf752c54"
  file: "/home/travis/build/opencirclesolutions/dynamo/dynamo-core/target/dynamo-core-1.0.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true